export const LOCATIONS = [
  // North America
  { id: 1,  lat: 40.7128,   lng: -74.0060,   country: 'USA',              city: 'New York City',      song: { title: 'Empire State of Mind',          artist: 'Jay-Z' } },
  { id: 2,  lat: 34.0522,   lng: -118.2437,  country: 'USA',              city: 'Los Angeles',        song: { title: 'California Love',               artist: '2Pac' } },
  { id: 3,  lat: 41.8781,   lng: -87.6298,   country: 'USA',              city: 'Chicago',            song: { title: 'Sweet Home Chicago',            artist: 'The Blues Brothers' } },
  { id: 4,  lat: 37.7749,   lng: -122.4194,  country: 'USA',              city: 'San Francisco',      song: { title: 'I Left My Heart in San Francisco', artist: 'Tony Bennett' } },
  { id: 5,  lat: 25.7617,   lng: -80.1918,   country: 'USA',              city: 'Miami',              song: { title: 'Miami',                         artist: 'Will Smith' } },
  { id: 6,  lat: 29.7604,   lng: -95.3698,   country: 'USA',              city: 'Houston',            song: { title: 'Houston',                       artist: 'Dean Martin' } },
  { id: 7,  lat: 47.6062,   lng: -122.3321,  country: 'USA',              city: 'Seattle',            song: { title: 'Come as You Are',               artist: 'Nirvana' } },
  { id: 8,  lat: 43.6532,   lng: -79.3832,   country: 'Canada',           city: 'Toronto',            song: { title: 'Started From the Bottom',       artist: 'Drake' } },
  { id: 9,  lat: 45.5051,   lng: -73.5571,   country: 'Canada',           city: 'Montreal',           song: { title: 'Hallelujah',                    artist: 'Leonard Cohen' } },
  { id: 10, lat: 49.2827,   lng: -123.1207,  country: 'Canada',           city: 'Vancouver',          song: { title: 'Ahead by a Century',            artist: 'The Tragically Hip' } },
  { id: 11, lat: 19.4326,   lng: -99.1332,   country: 'Mexico',           city: 'Mexico City',        song: { title: 'Cielito Lindo',                 artist: 'Mariachi Vargas de Tecalitlan' } },
  { id: 12, lat: 20.9674,   lng: -89.5926,   country: 'Mexico',           city: 'Merida',             song: { title: 'Besame Mucho',                  artist: 'Trio Los Panchos' } },
  // South America
  { id: 13, lat: -22.9068,  lng: -43.1729,   country: 'Brazil',           city: 'Rio de Janeiro',     song: { title: 'The Girl from Ipanema',         artist: 'Stan Getz' } },
  { id: 14, lat: -23.5505,  lng: -46.6333,   country: 'Brazil',           city: 'São Paulo',          song: { title: 'Mas Que Nada',                  artist: 'Sergio Mendes' } },
  { id: 15, lat: -34.6037,  lng: -58.3816,   country: 'Argentina',        city: 'Buenos Aires',       song: { title: 'Por Una Cabeza',                artist: 'Carlos Gardel' } },
  { id: 16, lat: -33.4489,  lng: -70.6693,   country: 'Chile',            city: 'Santiago',           song: { title: 'Gracias a la Vida',             artist: 'Mercedes Sosa' } },
  { id: 17, lat: -12.0464,  lng: -77.0428,   country: 'Peru',             city: 'Lima',               song: { title: 'El Condor Pasa',                artist: 'Simon & Garfunkel' } },
  { id: 18, lat: 4.7110,    lng: -74.0721,   country: 'Colombia',         city: 'Bogotá',             song: { title: 'La Camisa Negra',               artist: 'Juanes' } },
  { id: 19, lat: -0.1807,   lng: -78.4678,   country: 'Ecuador',          city: 'Quito',              song: { title: 'El Chulla Quiteño',             artist: 'Benítez y Valencia' } },
  { id: 20, lat: -15.7934,  lng: -47.8823,   country: 'Brazil',           city: 'Brasília',           song: { title: 'Aquarela do Brasil',            artist: 'Gal Costa' } },
  // Europe
  { id: 21, lat: 51.5074,   lng: -0.1278,    country: 'UK',               city: 'London',             song: { title: 'London Calling',                artist: 'The Clash' } },
  { id: 22, lat: 48.8566,   lng: 2.3522,     country: 'France',           city: 'Paris',              song: { title: 'La Vie en Rose',                artist: 'Edith Piaf' } },
  { id: 23, lat: 41.9028,   lng: 12.4964,    country: 'Italy',            city: 'Rome',               song: { title: 'Volare',                        artist: 'Domenico Modugno' } },
  { id: 24, lat: 40.4168,   lng: -3.7038,    country: 'Spain',            city: 'Madrid',             song: { title: 'Macarena',                      artist: 'Los Del Rio' } },
  { id: 25, lat: 41.3851,   lng: 2.1734,     country: 'Spain',            city: 'Barcelona',          song: { title: 'Barcelona',                     artist: 'Freddie Mercury' } },
  { id: 26, lat: 52.5200,   lng: 13.4050,    country: 'Germany',          city: 'Berlin',             song: { title: '99 Luftballons',                artist: 'Nena' } },
  { id: 27, lat: 48.1351,   lng: 11.5820,    country: 'Germany',          city: 'Munich',             song: { title: 'Atemlos durch die Nacht',       artist: 'Helene Fischer' } },
  { id: 28, lat: 52.3676,   lng: 4.9041,     country: 'Netherlands',      city: 'Amsterdam',          song: { title: 'Amsterdam',                     artist: 'Jacques Brel' } },
  { id: 29, lat: 48.2082,   lng: 16.3738,    country: 'Austria',          city: 'Vienna',             song: { title: 'The Blue Danube',               artist: 'Herbert von Karajan' } },
  { id: 30, lat: 50.0755,   lng: 14.4378,    country: 'Czech Republic',   city: 'Prague',             song: { title: 'The Moldau',                    artist: 'Rafael Kubelik' } },
  { id: 31, lat: 52.2297,   lng: 21.0122,    country: 'Poland',           city: 'Warsaw',             song: { title: 'Nocturne in E-flat major Op. 9 No. 2', artist: 'Frédéric Chopin' } },
  { id: 32, lat: 47.3769,   lng: 8.5417,     country: 'Switzerland',      city: 'Zurich',             song: { title: 'Edelweiss',                     artist: 'Rodgers & Hammerstein' } },
  { id: 33, lat: 59.9139,   lng: 10.7522,    country: 'Norway',           city: 'Oslo',               song: { title: 'Take On Me',                    artist: 'a-ha' } },
  { id: 34, lat: 55.6761,   lng: 12.5683,    country: 'Denmark',          city: 'Copenhagen',         song: { title: 'Wonderful Copenhagen',          artist: 'Danny Kaye' } },
  { id: 35, lat: 59.3293,   lng: 18.0686,    country: 'Sweden',           city: 'Stockholm',          song: { title: 'Dancing Queen',                 artist: 'ABBA' } },
  { id: 36, lat: 60.1699,   lng: 24.9384,    country: 'Finland',          city: 'Helsinki',           song: { title: 'Sandstorm',                     artist: 'Darude' } },
  { id: 37, lat: 47.4979,   lng: 19.0402,    country: 'Hungary',          city: 'Budapest',           song: { title: 'Gloomy Sunday',                 artist: 'Billie Holiday' } },
  { id: 38, lat: 37.9838,   lng: 23.7275,    country: 'Greece',           city: 'Athens',             song: { title: 'Zorba the Greek',               artist: 'Mikis Theodorakis' } },
  { id: 39, lat: 41.0082,   lng: 28.9784,    country: 'Turkey',           city: 'Istanbul',           song: { title: 'Istanbul Not Constantinople',   artist: 'They Might Be Giants' } },
  { id: 40, lat: 55.7558,   lng: 37.6173,    country: 'Russia',           city: 'Moscow',             song: { title: 'Moscow',                        artist: 'Genghis Khan' } },
  { id: 41, lat: 59.9311,   lng: 30.3609,    country: 'Russia',           city: 'St. Petersburg',     song: { title: 'Kalinka',                       artist: 'Red Army Choir' } },
  { id: 42, lat: 38.7223,   lng: -9.1393,    country: 'Portugal',         city: 'Lisbon',             song: { title: 'Estranha Forma de Vida',        artist: 'Amalia Rodrigues' } },
  { id: 43, lat: 64.1265,   lng: -21.8174,   country: 'Iceland',          city: 'Reykjavik',          song: { title: 'Human Behaviour',               artist: 'Björk' } },
  { id: 44, lat: 53.3498,   lng: -6.2603,    country: 'Ireland',          city: 'Dublin',             song: { title: 'Whiskey in the Jar',            artist: 'Thin Lizzy' } },
  { id: 45, lat: 50.8503,   lng: 4.3517,     country: 'Belgium',          city: 'Brussels',           song: { title: 'Ne Me Quitte Pas',              artist: 'Jacques Brel' } },
  { id: 46, lat: 45.8150,   lng: 15.9819,    country: 'Croatia',          city: 'Zagreb',             song: { title: 'Moja Stikla',                   artist: 'Severina' } },
  { id: 47, lat: 42.6977,   lng: 23.3219,    country: 'Bulgaria',         city: 'Sofia',              song: { title: 'Dilmano Dilbero',               artist: 'Le Mystere des Voix Bulgares' } },
  { id: 48, lat: 44.8176,   lng: 20.4633,    country: 'Serbia',           city: 'Belgrade',           song: { title: 'Djurdjevdan',                   artist: 'Emir Kusturica' } },
  { id: 49, lat: 46.0569,   lng: 14.5058,    country: 'Slovenia',         city: 'Ljubljana',          song: { title: 'Tih deževen dan',               artist: 'Vlado Kreslin' } },
  // Africa
  { id: 50, lat: 30.0444,   lng: 31.2357,    country: 'Egypt',            city: 'Cairo',              song: { title: 'Inta Omri',                     artist: 'Umm Kulthum' } },
  { id: 51, lat: -33.9249,  lng: 18.4241,    country: 'South Africa',     city: 'Cape Town',          song: { title: 'Pata Pata',                     artist: 'Miriam Makeba' } },
  { id: 52, lat: -26.2041,  lng: 28.0473,    country: 'South Africa',     city: 'Johannesburg',       song: { title: 'Bring Him Back Home',           artist: 'Hugh Masekela' } },
  { id: 53, lat: -1.2921,   lng: 36.8219,    country: 'Kenya',            city: 'Nairobi',            song: { title: 'Jambo Bwana',                   artist: 'Them Mushrooms' } },
  { id: 54, lat: 5.6037,    lng: -0.1870,    country: 'Ghana',            city: 'Accra',              song: { title: 'Ye',                            artist: 'Burna Boy' } },
  { id: 55, lat: 6.5244,    lng: 3.3792,     country: 'Nigeria',          city: 'Lagos',              song: { title: 'Lady',                          artist: 'Fela Kuti' } },
  { id: 56, lat: 31.6295,   lng: -7.9811,    country: 'Morocco',          city: 'Marrakech',          song: { title: 'Desert Rose',                   artist: 'Sting' } },
  { id: 57, lat: 33.9716,   lng: -6.8498,    country: 'Morocco',          city: 'Rabat',              song: { title: 'Aicha',                         artist: 'Khaled' } },
  { id: 58, lat: 14.6928,   lng: -17.4467,   country: 'Senegal',          city: 'Dakar',              song: { title: '7 Seconds',                     artist: 'Youssou N\'Dour' } },
  { id: 59, lat: -4.3220,   lng: 15.3220,    country: 'DR Congo',         city: 'Kinshasa',           song: { title: 'Nakombela',                     artist: 'Fally Ipupa' } },
  { id: 60, lat: -18.9137,  lng: 47.5361,    country: 'Madagascar',       city: 'Antananarivo',       song: { title: 'Tsarabanjina',                  artist: 'Tarika' } },
  // Asia
  { id: 61, lat: 35.6762,   lng: 139.6503,   country: 'Japan',            city: 'Tokyo',              song: { title: 'Sukiyaki',                      artist: 'Kyu Sakamoto' } },
  { id: 62, lat: 34.6937,   lng: 135.5023,   country: 'Japan',            city: 'Osaka',              song: { title: 'Koi',                           artist: 'Gen Hoshino' } },
  { id: 63, lat: 35.0116,   lng: 135.7681,   country: 'Japan',            city: 'Kyoto',              song: { title: 'Sakura Sakura',                 artist: 'Yo-Yo Ma' } },
  { id: 64, lat: 37.5665,   lng: 126.9780,   country: 'South Korea',      city: 'Seoul',              song: { title: 'Gangnam Style',                 artist: 'PSY' } },
  { id: 65, lat: 35.1796,   lng: 129.0756,   country: 'South Korea',      city: 'Busan',              song: { title: 'Dynamite',                      artist: 'BTS' } },
  { id: 66, lat: 39.9042,   lng: 116.4074,   country: 'China',            city: 'Beijing',            song: { title: 'Mo Li Hua',                     artist: 'Song Zuying' } },
  { id: 67, lat: 31.2304,   lng: 121.4737,   country: 'China',            city: 'Shanghai',           song: { title: 'Ye Shanghai',                   artist: 'Zhou Xuan' } },
  { id: 68, lat: 22.3193,   lng: 114.1694,   country: 'Hong Kong',        city: 'Hong Kong',          song: { title: 'Under the Lion Rock',           artist: 'Roman Tam' } },
  { id: 69, lat: 1.3521,    lng: 103.8198,   country: 'Singapore',        city: 'Singapore',          song: { title: 'Home',                          artist: 'Kit Chan' } },
  { id: 70, lat: 13.7563,   lng: 100.5018,   country: 'Thailand',         city: 'Bangkok',            song: { title: 'One Night in Bangkok',          artist: 'Murray Head' } },
  { id: 71, lat: 10.8231,   lng: 106.6297,   country: 'Vietnam',          city: 'Ho Chi Minh City',   song: { title: 'Tình Ca',                       artist: 'Pham Duy' } },
  { id: 72, lat: 21.0285,   lng: 105.8542,   country: 'Vietnam',          city: 'Hanoi',              song: { title: 'Noi Buon Hoa Phuong',          artist: 'Thanh Tuyen' } },
  { id: 73, lat: 3.1390,    lng: 101.6869,   country: 'Malaysia',         city: 'Kuala Lumpur',       song: { title: 'Rasa Sayang',                   artist: 'Traditional Malaysian' } },
  { id: 74, lat: -6.2088,   lng: 106.8456,   country: 'Indonesia',        city: 'Jakarta',            song: { title: 'Bengawan Solo',                 artist: 'Gesang' } },
  { id: 75, lat: -8.4095,   lng: 115.1889,   country: 'Indonesia',        city: 'Bali',               song: { title: 'Bali Ha\'i',                    artist: 'Original Broadway Cast South Pacific' } },
  { id: 76, lat: 14.5995,   lng: 120.9842,   country: 'Philippines',      city: 'Manila',             song: { title: 'Anak',                          artist: 'Freddie Aguilar' } },
  { id: 77, lat: 28.7041,   lng: 77.1025,    country: 'India',            city: 'New Delhi',          song: { title: 'Jai Ho',                        artist: 'A.R. Rahman' } },
  { id: 78, lat: 19.0760,   lng: 72.8777,    country: 'India',            city: 'Mumbai',             song: { title: 'Chaiyya Chaiyya',               artist: 'Sukhwinder Singh' } },
  { id: 79, lat: 12.9716,   lng: 77.5946,    country: 'India',            city: 'Bangalore',          song: { title: 'Kolaveri Di',                   artist: 'Dhanush' } },
  { id: 80, lat: 25.2048,   lng: 55.2708,    country: 'UAE',              city: 'Dubai',              song: { title: 'Habibi Ya Nour El Ain',         artist: 'Amr Diab' } },
  { id: 81, lat: 24.6877,   lng: 46.7219,    country: 'Saudi Arabia',     city: 'Riyadh',             song: { title: 'Bent El Sultan',                artist: 'Mohammed Abdu' } },
  { id: 82, lat: 31.7683,   lng: 35.2137,    country: 'Israel',           city: 'Jerusalem',          song: { title: 'Jerusalem of Gold',             artist: 'Naomi Shemer' } },
  { id: 83, lat: 32.0853,   lng: 34.7818,    country: 'Israel',           city: 'Tel Aviv',           song: { title: 'Milim',                         artist: 'Idan Raichel' } },
  { id: 84, lat: 41.2995,   lng: 69.2401,    country: 'Uzbekistan',       city: 'Tashkent',           song: { title: 'Dudarai',                       artist: 'Dimash Kudaibergen' } },
  { id: 85, lat: 43.2220,   lng: 76.8512,    country: 'Kazakhstan',       city: 'Almaty',             song: { title: 'S.O.S.',                        artist: 'Dimash Kudaibergen' } },
  { id: 86, lat: 23.8103,   lng: 90.4125,    country: 'Bangladesh',       city: 'Dhaka',              song: { title: 'Amar Shonar Bangla',            artist: 'Rabindranath Tagore' } },
  { id: 87, lat: 6.9271,    lng: 79.8612,    country: 'Sri Lanka',        city: 'Colombo',            song: { title: 'Sanda Eliya',                   artist: 'W.D. Amaradeva' } },
  // Oceania
  { id: 88, lat: -33.8688,  lng: 151.2093,   country: 'Australia',        city: 'Sydney',             song: { title: 'Down Under',                    artist: 'Men at Work' } },
  { id: 89, lat: -37.8136,  lng: 144.9631,   country: 'Australia',        city: 'Melbourne',          song: { title: 'Flame Trees',                   artist: 'Cold Chisel' } },
  { id: 90, lat: -27.4698,  lng: 153.0251,   country: 'Australia',        city: 'Brisbane',           song: { title: 'Great Southern Land',           artist: 'Icehouse' } },
  { id: 91, lat: -31.9505,  lng: 115.8605,   country: 'Australia',        city: 'Perth',              song: { title: 'Beds Are Burning',              artist: 'Midnight Oil' } },
  { id: 92, lat: -36.8485,  lng: 174.7633,   country: 'New Zealand',      city: 'Auckland',           song: { title: 'Don\'t Dream It\'s Over',       artist: 'Crowded House' } },
  { id: 93, lat: -41.2865,  lng: 174.7762,   country: 'New Zealand',      city: 'Wellington',         song: { title: 'Slice of Heaven',               artist: 'Dave Dobbyn' } },
  // Central America & Caribbean
  { id: 94, lat: 9.9281,    lng: -84.0907,   country: 'Costa Rica',       city: 'San José',           song: { title: 'Guantanamera',                  artist: 'Celia Cruz' } },
  { id: 95, lat: 23.1136,   lng: -82.3666,   country: 'Cuba',             city: 'Havana',             song: { title: 'Chan Chan',                     artist: 'Compay Segundo' } },
  { id: 96, lat: 18.4861,   lng: -69.9312,   country: 'Dominican Republic', city: 'Santo Domingo',    song: { title: 'Obsesion',                      artist: 'Aventura' } },
  { id: 97, lat: 8.9936,    lng: -79.5197,   country: 'Panama',           city: 'Panama City',        song: { title: 'El General',                    artist: 'El General' } },
  // Remote & unique
  { id: 98,  lat: -54.8019, lng: -68.3030,   country: 'Argentina',        city: 'Ushuaia',            song: { title: 'El día que me quieras',         artist: 'Carlos Gardel' } },
  { id: 99,  lat: 27.1751,  lng: 78.0421,    country: 'India',            city: 'Agra',               song: { title: 'Dil Se Re',                     artist: 'A.R. Rahman' } },
  { id: 100, lat: 53.9006,  lng: 27.5590,    country: 'Belarus',          city: 'Minsk',              song: { title: 'Katyusha',                      artist: 'Red Army Choir' } },
];
