export const LOCATIONS = [
  // North America
  { id: 1,  lat: 40.7128,   lng: -74.0060,   country: 'USA',              city: 'New York City',      song: { title: 'Empire State of Mind',          artist: 'Jay-Z' } },
  { id: 2,  lat: 34.0522,   lng: -118.2437,  country: 'USA',              city: 'Los Angeles',        song: { title: 'California Love',               artist: '2Pac' } },
  { id: 3,  lat: 41.8781,   lng: -87.6298,   country: 'USA',              city: 'Chicago',            song: { title: 'Sweet Home Chicago',            artist: 'The Blues Brothers' } },
  { id: 4,  lat: 37.7749,   lng: -122.4194,  country: 'USA',              city: 'San Francisco',      song: { title: 'I Left My Heart in San Francisco', artist: 'Tony Bennett' } },
  { id: 5,  lat: 25.7617,   lng: -80.1918,   country: 'USA',              city: 'Miami',              song: { title: 'Miami',                         artist: 'Will Smith' } },
  { id: 6,  lat: 29.7604,   lng: -95.3698,   country: 'USA',              city: 'Houston',            song: { title: 'Houston',                       artist: 'Dean Martin' } },
  { id: 7,  lat: 47.6062,   lng: -122.3321,  country: 'USA',              city: 'Seattle',            song: { title: 'Come as You Are',               artist: 'Nirvana' } },
  { id: 8,  lat: 43.6532,   lng: -79.3832,   country: 'Canada',           city: 'Toronto',            song: { title: 'Started From the Bottom',       artist: 'Drake' } },
  { id: 9,  lat: 45.5051,   lng: -73.5571,   country: 'Canada',           city: 'Montreal',           song: { title: 'Hallelujah',                    artist: 'Leonard Cohen' } },
  { id: 10, lat: 49.2827,   lng: -123.1207,  country: 'Canada',           city: 'Vancouver',          song: { title: 'Ahead by a Century',            artist: 'The Tragically Hip' } },
  { id: 11, lat: 19.4326,   lng: -99.1332,   country: 'Mexico',           city: 'Mexico City',        song: { title: 'Cielito Lindo',                 artist: 'Mariachi Vargas de Tecalitlan' } },
  { id: 12, lat: 20.9674,   lng: -89.5926,   country: 'Mexico',           city: 'Merida',             song: { title: 'Besame Mucho',                  artist: 'Trio Los Panchos' } },
  // South America
  { id: 13, lat: -22.9068,  lng: -43.1729,   country: 'Brazil',           city: 'Rio de Janeiro',     song: { title: 'The Girl from Ipanema',         artist: 'Stan Getz' } },
  { id: 14, lat: -23.5505,  lng: -46.6333,   country: 'Brazil',           city: 'São Paulo',          song: { title: 'Mas Que Nada',                  artist: 'Sergio Mendes' } },
  { id: 15, lat: -34.6037,  lng: -58.3816,   country: 'Argentina',        city: 'Buenos Aires',       song: { title: 'Por Una Cabeza',                artist: 'Carlos Gardel' } },
  { id: 16, lat: -33.4489,  lng: -70.6693,   country: 'Chile',            city: 'Santiago',           song: { title: 'Gracias a la Vida',             artist: 'Mercedes Sosa' } },
  { id: 17, lat: -12.0464,  lng: -77.0428,   country: 'Peru',             city: 'Lima',               song: { title: 'El Condor Pasa',                artist: 'Simon & Garfunkel' } },
  { id: 18, lat: 4.7110,    lng: -74.0721,   country: 'Colombia',         city: 'Bogotá',             song: { title: 'La Camisa Negra',               artist: 'Juanes' } },
  { id: 19, lat: -0.1807,   lng: -78.4678,   country: 'Ecuador',          city: 'Quito',              song: { title: 'El Chulla Quiteño',             artist: 'Benítez y Valencia' } },
  { id: 20, lat: -15.7934,  lng: -47.8823,   country: 'Brazil',           city: 'Brasília',           song: { title: 'Aquarela do Brasil',            artist: 'Gal Costa' } },
  // Europe
  { id: 21, lat: 51.5074,   lng: -0.1278,    country: 'UK',               city: 'London',             song: { title: 'London Calling',                artist: 'The Clash' } },
  { id: 22, lat: 48.8566,   lng: 2.3522,     country: 'France',           city: 'Paris',              song: { title: 'La Vie en Rose',                artist: 'Edith Piaf' } },
  { id: 23, lat: 41.9028,   lng: 12.4964,    country: 'Italy',            city: 'Rome',               song: { title: 'Volare',                        artist: 'Domenico Modugno' } },
  { id: 24, lat: 40.4168,   lng: -3.7038,    country: 'Spain',            city: 'Madrid',             song: { title: 'Macarena',                      artist: 'Los Del Rio' } },
  { id: 25, lat: 41.3851,   lng: 2.1734,     country: 'Spain',            city: 'Barcelona',          song: { title: 'Barcelona',                     artist: 'Freddie Mercury' } },
  { id: 26, lat: 52.5200,   lng: 13.4050,    country: 'Germany',          city: 'Berlin',             song: { title: '99 Luftballons',                artist: 'Nena' } },
  { id: 27, lat: 48.1351,   lng: 11.5820,    country: 'Germany',          city: 'Munich',             song: { title: 'Atemlos durch die Nacht',       artist: 'Helene Fischer' } },
  { id: 28, lat: 52.3676,   lng: 4.9041,     country: 'Netherlands',      city: 'Amsterdam',          song: { title: 'Amsterdam',                     artist: 'Jacques Brel' } },
  { id: 29, lat: 48.2082,   lng: 16.3738,    country: 'Austria',          city: 'Vienna',             song: { title: 'The Blue Danube',               artist: 'Herbert von Karajan' } },
  { id: 30, lat: 50.0755,   lng: 14.4378,    country: 'Czech Republic',   city: 'Prague',             song: { title: 'The Moldau',                    artist: 'Rafael Kubelik' } },
  { id: 31, lat: 52.2297,   lng: 21.0122,    country: 'Poland',           city: 'Warsaw',             song: { title: 'Nocturne in E-flat major Op. 9 No. 2', artist: 'Frédéric Chopin' } },
  { id: 32, lat: 47.3769,   lng: 8.5417,     country: 'Switzerland',      city: 'Zurich',             song: { title: 'Edelweiss',                     artist: 'Rodgers & Hammerstein' } },
  { id: 33, lat: 59.9139,   lng: 10.7522,    country: 'Norway',           city: 'Oslo',               song: { title: 'Take On Me',                    artist: 'a-ha' } },
  { id: 34, lat: 55.6761,   lng: 12.5683,    country: 'Denmark',          city: 'Copenhagen',         song: { title: 'Wonderful Copenhagen',          artist: 'Danny Kaye' } },
  { id: 35, lat: 59.3293,   lng: 18.0686,    country: 'Sweden',           city: 'Stockholm',          song: { title: 'Dancing Queen',                 artist: 'ABBA' } },
  { id: 36, lat: 60.1699,   lng: 24.9384,    country: 'Finland',          city: 'Helsinki',           song: { title: 'Sandstorm',                     artist: 'Darude' } },
  { id: 37, lat: 47.4979,   lng: 19.0402,    country: 'Hungary',          city: 'Budapest',           song: { title: 'Gloomy Sunday',                 artist: 'Billie Holiday' } },
  { id: 38, lat: 37.9838,   lng: 23.7275,    country: 'Greece',           city: 'Athens',             song: { title: 'Zorba the Greek',               artist: 'Mikis Theodorakis' } },
  { id: 39, lat: 41.0082,   lng: 28.9784,    country: 'Turkey',           city: 'Istanbul',           song: { title: 'Istanbul Not Constantinople',   artist: 'They Might Be Giants' } },
  { id: 40, lat: 55.7558,   lng: 37.6173,    country: 'Russia',           city: 'Moscow',             song: { title: 'Moscow',                        artist: 'Genghis Khan' } },
  { id: 41, lat: 59.9311,   lng: 30.3609,    country: 'Russia',           city: 'St. Petersburg',     song: { title: 'Kalinka',                       artist: 'Red Army Choir' } },
  { id: 42, lat: 38.7223,   lng: -9.1393,    country: 'Portugal',         city: 'Lisbon',             song: { title: 'Estranha Forma de Vida',        artist: 'Amalia Rodrigues' } },
  { id: 43, lat: 64.1265,   lng: -21.8174,   country: 'Iceland',          city: 'Reykjavik',          song: { title: 'Human Behaviour',               artist: 'Björk' } },
  { id: 44, lat: 53.3498,   lng: -6.2603,    country: 'Ireland',          city: 'Dublin',             song: { title: 'Whiskey in the Jar',            artist: 'Thin Lizzy' } },
  { id: 45, lat: 50.8503,   lng: 4.3517,     country: 'Belgium',          city: 'Brussels',           song: { title: 'Ne Me Quitte Pas',              artist: 'Jacques Brel' } },
  { id: 46, lat: 45.8150,   lng: 15.9819,    country: 'Croatia',          city: 'Zagreb',             song: { title: 'Moja Stikla',                   artist: 'Severina' } },
  { id: 47, lat: 42.6977,   lng: 23.3219,    country: 'Bulgaria',         city: 'Sofia',              song: { title: 'Dilmano Dilbero',               artist: 'Le Mystere des Voix Bulgares' } },
  { id: 48, lat: 44.8176,   lng: 20.4633,    country: 'Serbia',           city: 'Belgrade',           song: { title: 'Djurdjevdan',                   artist: 'Emir Kusturica' } },
  { id: 49, lat: 46.0569,   lng: 14.5058,    country: 'Slovenia',         city: 'Ljubljana',          song: { title: 'Tih deževen dan',               artist: 'Vlado Kreslin' } },
  // Africa
  { id: 50, lat: 30.0444,   lng: 31.2357,    country: 'Egypt',            city: 'Cairo',              song: { title: 'Inta Omri',                     artist: 'Umm Kulthum' } },
  { id: 51, lat: -33.9249,  lng: 18.4241,    country: 'South Africa',     city: 'Cape Town',          song: { title: 'Pata Pata',                     artist: 'Miriam Makeba' } },
  { id: 52, lat: -26.2041,  lng: 28.0473,    country: 'South Africa',     city: 'Johannesburg',       song: { title: 'Bring Him Back Home',           artist: 'Hugh Masekela' } },
  { id: 53, lat: -1.2921,   lng: 36.8219,    country: 'Kenya',            city: 'Nairobi',            song: { title: 'Jambo Bwana',                   artist: 'Them Mushrooms' } },
  { id: 54, lat: 5.6037,    lng: -0.1870,    country: 'Ghana',            city: 'Accra',              song: { title: 'Ye',                            artist: 'Burna Boy' } },
  { id: 55, lat: 6.5244,    lng: 3.3792,     country: 'Nigeria',          city: 'Lagos',              song: { title: 'Lady',                          artist: 'Fela Kuti' } },
  { id: 56, lat: 31.6295,   lng: -7.9811,    country: 'Morocco',          city: 'Marrakech',          song: { title: 'Desert Rose',                   artist: 'Sting' } },
  { id: 57, lat: 33.9716,   lng: -6.8498,    country: 'Morocco',          city: 'Rabat',              song: { title: 'Aicha',                         artist: 'Khaled' } },
  { id: 58, lat: 14.6928,   lng: -17.4467,   country: 'Senegal',          city: 'Dakar',              song: { title: '7 Seconds',                     artist: 'Youssou N\'Dour' } },
  { id: 59, lat: -4.3220,   lng: 15.3220,    country: 'DR Congo',         city: 'Kinshasa',           song: { title: 'Nakombela',                     artist: 'Fally Ipupa' } },
  { id: 60, lat: -18.9137,  lng: 47.5361,    country: 'Madagascar',       city: 'Antananarivo',       song: { title: 'Tsarabanjina',                  artist: 'Tarika' } },
  // Asia
  { id: 61, lat: 35.6762,   lng: 139.6503,   country: 'Japan',            city: 'Tokyo',              song: { title: 'Sukiyaki',                      artist: 'Kyu Sakamoto' } },
  { id: 62, lat: 34.6937,   lng: 135.5023,   country: 'Japan',            city: 'Osaka',              song: { title: 'Koi',                           artist: 'Gen Hoshino' } },
  { id: 63, lat: 35.0116,   lng: 135.7681,   country: 'Japan',            city: 'Kyoto',              song: { title: 'Sakura Sakura',                 artist: 'Yo-Yo Ma' } },
  { id: 64, lat: 37.5665,   lng: 126.9780,   country: 'South Korea',      city: 'Seoul',              song: { title: 'Gangnam Style',                 artist: 'PSY' } },
  { id: 65, lat: 35.1796,   lng: 129.0756,   country: 'South Korea',      city: 'Busan',              song: { title: 'Dynamite',                      artist: 'BTS' } },
  { id: 66, lat: 39.9042,   lng: 116.4074,   country: 'China',            city: 'Beijing',            song: { title: 'Mo Li Hua',                     artist: 'Song Zuying' } },
  { id: 67, lat: 31.2304,   lng: 121.4737,   country: 'China',            city: 'Shanghai',           song: { title: 'Ye Shanghai',                   artist: 'Zhou Xuan' } },
  { id: 68, lat: 22.3193,   lng: 114.1694,   country: 'Hong Kong',        city: 'Hong Kong',          song: { title: 'Under the Lion Rock',           artist: 'Roman Tam' } },
  { id: 69, lat: 1.3521,    lng: 103.8198,   country: 'Singapore',        city: 'Singapore',          song: { title: 'Home',                          artist: 'Kit Chan' } },
  { id: 70, lat: 13.7563,   lng: 100.5018,   country: 'Thailand',         city: 'Bangkok',            song: { title: 'One Night in Bangkok',          artist: 'Murray Head' } },
  { id: 71, lat: 10.8231,   lng: 106.6297,   country: 'Vietnam',          city: 'Ho Chi Minh City',   song: { title: 'Tình Ca',                       artist: 'Pham Duy' } },
  { id: 72, lat: 21.0285,   lng: 105.8542,   country: 'Vietnam',          city: 'Hanoi',              song: { title: 'Noi Buon Hoa Phuong',          artist: 'Thanh Tuyen' } },
  { id: 73, lat: 3.1390,    lng: 101.6869,   country: 'Malaysia',         city: 'Kuala Lumpur',       song: { title: 'Rasa Sayang',                   artist: 'Traditional Malaysian' } },
  { id: 74, lat: -6.2088,   lng: 106.8456,   country: 'Indonesia',        city: 'Jakarta',            song: { title: 'Bengawan Solo',                 artist: 'Gesang' } },
  { id: 75, lat: -8.4095,   lng: 115.1889,   country: 'Indonesia',        city: 'Bali',               song: { title: 'Bali Ha\'i',                    artist: 'Original Broadway Cast South Pacific' } },
  { id: 76, lat: 14.5995,   lng: 120.9842,   country: 'Philippines',      city: 'Manila',             song: { title: 'Anak',                          artist: 'Freddie Aguilar' } },
  { id: 77, lat: 28.7041,   lng: 77.1025,    country: 'India',            city: 'New Delhi',          song: { title: 'Jai Ho',                        artist: 'A.R. Rahman' } },
  { id: 78, lat: 19.0760,   lng: 72.8777,    country: 'India',            city: 'Mumbai',             song: { title: 'Chaiyya Chaiyya',               artist: 'Sukhwinder Singh' } },
  { id: 79, lat: 12.9716,   lng: 77.5946,    country: 'India',            city: 'Bangalore',          song: { title: 'Kolaveri Di',                   artist: 'Dhanush' } },
  { id: 80, lat: 25.2048,   lng: 55.2708,    country: 'UAE',              city: 'Dubai',              song: { title: 'Habibi Ya Nour El Ain',         artist: 'Amr Diab' } },
  { id: 81, lat: 24.6877,   lng: 46.7219,    country: 'Saudi Arabia',     city: 'Riyadh',             song: { title: 'Bent El Sultan',                artist: 'Mohammed Abdu' } },
  { id: 82, lat: 31.7683,   lng: 35.2137,    country: 'Israel',           city: 'Jerusalem',          song: { title: 'Jerusalem of Gold',             artist: 'Naomi Shemer' } },
  { id: 83, lat: 32.0853,   lng: 34.7818,    country: 'Israel',           city: 'Tel Aviv',           song: { title: 'Milim',                         artist: 'Idan Raichel' } },
  { id: 84, lat: 41.2995,   lng: 69.2401,    country: 'Uzbekistan',       city: 'Tashkent',           song: { title: 'Dudarai',                       artist: 'Dimash Kudaibergen' } },
  { id: 85, lat: 43.2220,   lng: 76.8512,    country: 'Kazakhstan',       city: 'Almaty',             song: { title: 'S.O.S.',                        artist: 'Dimash Kudaibergen' } },
  { id: 86, lat: 23.8103,   lng: 90.4125,    country: 'Bangladesh',       city: 'Dhaka',              song: { title: 'Amar Shonar Bangla',            artist: 'Rabindranath Tagore' } },
  { id: 87, lat: 6.9271,    lng: 79.8612,    country: 'Sri Lanka',        city: 'Colombo',            song: { title: 'Sanda Eliya',                   artist: 'W.D. Amaradeva' } },
  // Oceania
  { id: 88, lat: -33.8688,  lng: 151.2093,   country: 'Australia',        city: 'Sydney',             song: { title: 'Down Under',                    artist: 'Men at Work' } },
  { id: 89, lat: -37.8136,  lng: 144.9631,   country: 'Australia',        city: 'Melbourne',          song: { title: 'Flame Trees',                   artist: 'Cold Chisel' } },
  { id: 90, lat: -27.4698,  lng: 153.0251,   country: 'Australia',        city: 'Brisbane',           song: { title: 'Great Southern Land',           artist: 'Icehouse' } },
  { id: 91, lat: -31.9505,  lng: 115.8605,   country: 'Australia',        city: 'Perth',              song: { title: 'Beds Are Burning',              artist: 'Midnight Oil' } },
  { id: 92, lat: -36.8485,  lng: 174.7633,   country: 'New Zealand',      city: 'Auckland',           song: { title: 'Don\'t Dream It\'s Over',       artist: 'Crowded House' } },
  { id: 93, lat: -41.2865,  lng: 174.7762,   country: 'New Zealand',      city: 'Wellington',         song: { title: 'Slice of Heaven',               artist: 'Dave Dobbyn' } },
  // Central America & Caribbean
  { id: 94, lat: 9.9281,    lng: -84.0907,   country: 'Costa Rica',       city: 'San José',           song: { title: 'Guantanamera',                  artist: 'Celia Cruz' } },
  { id: 95, lat: 23.1136,   lng: -82.3666,   country: 'Cuba',             city: 'Havana',             song: { title: 'Chan Chan',                     artist: 'Compay Segundo' } },
  { id: 96, lat: 18.4861,   lng: -69.9312,   country: 'Dominican Republic', city: 'Santo Domingo',    song: { title: 'Obsesion',                      artist: 'Aventura' } },
  { id: 97, lat: 8.9936,    lng: -79.5197,   country: 'Panama',           city: 'Panama City',        song: { title: 'El General',                    artist: 'El General' } },
  // Remote & unique
  { id: 98,  lat: -54.8019, lng: -68.3030,   country: 'Argentina',        city: 'Ushuaia',            song: { title: 'El día que me quieras',         artist: 'Carlos Gardel' } },
  { id: 99,  lat: 27.1751,  lng: 78.0421,    country: 'India',            city: 'Agra',               song: { title: 'Dil Se Re',                     artist: 'A.R. Rahman' } },
  { id: 100, lat: 53.9006,  lng: 27.5590,    country: 'Belarus',          city: 'Minsk',              song: { title: 'Katyusha',                      artist: 'Red Army Choir' } },
  // North America (additional)
  { id: 101, lat: 29.9511,  lng: -90.0715,  country: 'USA',              city: 'New Orleans',        song: { title: 'When the Saints Go Marching In', artist: 'Louis Armstrong' } },
  { id: 102, lat: 36.1627,  lng: -86.7816,  country: 'USA',              city: 'Nashville',          song: { title: 'Tennessee Whiskey',              artist: 'Chris Stapleton' } },
  { id: 103, lat: 39.7392,  lng: -104.9903, country: 'USA',              city: 'Denver',             song: { title: 'Rocky Mountain High',            artist: 'John Denver' } },
  { id: 104, lat: 33.4484,  lng: -112.0740, country: 'USA',              city: 'Phoenix',            song: { title: 'Take It Easy',                   artist: 'Eagles' } },
  { id: 105, lat: 42.3601,  lng: -71.0589,  country: 'USA',              city: 'Boston',             song: { title: 'More Than a Feeling',            artist: 'Boston' } },
  { id: 106, lat: 45.5152,  lng: -122.6784, country: 'USA',              city: 'Portland',           song: { title: 'Hunger Strike',                  artist: 'Temple of the Dog' } },
  { id: 107, lat: 36.1699,  lng: -115.1398, country: 'USA',              city: 'Las Vegas',          song: { title: 'Viva Las Vegas',                 artist: 'Elvis Presley' } },
  { id: 108, lat: 44.9778,  lng: -93.2650,  country: 'USA',              city: 'Minneapolis',        song: { title: 'Purple Rain',                    artist: 'Prince' } },
  { id: 109, lat: 45.4215,  lng: -75.6972,  country: 'Canada',           city: 'Ottawa',             song: { title: 'Summer of \'69',                 artist: 'Bryan Adams' } },
  { id: 110, lat: 51.0447,  lng: -114.0719, country: 'Canada',           city: 'Calgary',            song: { title: 'Alberta Bound',                  artist: 'Gordon Lightfoot' } },
  { id: 111, lat: 20.6597,  lng: -103.3496, country: 'Mexico',           city: 'Guadalajara',        song: { title: 'Guadalajara',                    artist: 'Mariachi Vargas de Tecalitlan' } },
  { id: 112, lat: 25.6866,  lng: -100.3161, country: 'Mexico',           city: 'Monterrey',          song: { title: 'La Incondicional',               artist: 'Luis Miguel' } },
  // South America (additional)
  { id: 113, lat: 6.2476,   lng: -75.5658,  country: 'Colombia',         city: 'Medellín',           song: { title: 'La Bicicleta',                   artist: 'Carlos Vives' } },
  { id: 114, lat: -34.9011, lng: -56.1645,  country: 'Uruguay',          city: 'Montevideo',         song: { title: 'La Cumparsita',                  artist: 'Gerardo Matos Rodriguez' } },
  { id: 115, lat: -16.5000, lng: -68.1193,  country: 'Bolivia',          city: 'La Paz',             song: { title: 'Llorando Se Fue',                artist: 'Los Kjarkas' } },
  { id: 116, lat: 10.3910,  lng: -75.4794,  country: 'Colombia',         city: 'Cartagena',          song: { title: 'Hips Don\'t Lie',                artist: 'Shakira' } },
  { id: 117, lat: -13.5319, lng: -71.9675,  country: 'Peru',             city: 'Cusco',              song: { title: 'El Condor Pasa',                 artist: 'Los Incas' } },
  { id: 118, lat: -25.2867, lng: -57.6470,  country: 'Paraguay',         city: 'Asunción',           song: { title: 'Recuerdos de Ypacarai',          artist: 'Los Indios Tabajaras' } },
  { id: 119, lat: -8.0476,  lng: -34.8770,  country: 'Brazil',           city: 'Recife',             song: { title: 'Asa Branca',                     artist: 'Luiz Gonzaga' } },
  { id: 120, lat: -12.9714, lng: -38.5014,  country: 'Brazil',           city: 'Salvador',           song: { title: 'Odara',                          artist: 'Caetano Veloso' } },
  { id: 121, lat: -2.1962,  lng: -79.8862,  country: 'Ecuador',          city: 'Guayaquil',          song: { title: 'Vasija de Barro',                artist: 'Benitez y Valencia' } },
  { id: 122, lat: -31.4201, lng: -64.1888,  country: 'Argentina',        city: 'Córdoba',            song: { title: 'De Musica Ligera',               artist: 'Soda Stereo' } },
  // Europe (additional)
  { id: 123, lat: 43.7696,  lng: 11.2558,   country: 'Italy',            city: 'Florence',           song: { title: 'O Mio Babbino Caro',             artist: 'Maria Callas' } },
  { id: 124, lat: 45.4408,  lng: 12.3155,   country: 'Italy',            city: 'Venice',             song: { title: 'Barcarolle',                     artist: 'Jacques Offenbach' } },
  { id: 125, lat: 40.8518,  lng: 14.2681,   country: 'Italy',            city: 'Naples',             song: { title: 'O Sole Mio',                     artist: 'Luciano Pavarotti' } },
  { id: 126, lat: 43.7102,  lng: 7.2620,    country: 'France',           city: 'Nice',               song: { title: 'La Mer',                         artist: 'Charles Trenet' } },
  { id: 127, lat: 45.7640,  lng: 4.8357,    country: 'France',           city: 'Lyon',               song: { title: 'Non je ne regrette rien',        artist: 'Edith Piaf' } },
  { id: 128, lat: 37.3891,  lng: -5.9845,   country: 'Spain',            city: 'Seville',            song: { title: 'Sevilla',                        artist: 'Isaac Albeniz' } },
  { id: 129, lat: 39.4699,  lng: -0.3763,   country: 'Spain',            city: 'Valencia',           song: { title: 'Mediterraneo',                   artist: 'Joan Manuel Serrat' } },
  { id: 130, lat: 53.5753,  lng: 10.0153,   country: 'Germany',          city: 'Hamburg',            song: { title: 'Lady in Black',                  artist: 'Uriah Heep' } },
  { id: 131, lat: 50.9333,  lng: 6.9500,    country: 'Germany',          city: 'Cologne',            song: { title: 'Major Tom',                      artist: 'Peter Schilling' } },
  { id: 132, lat: 55.9533,  lng: -3.1883,   country: 'UK',               city: 'Edinburgh',          song: { title: 'Flower of Scotland',             artist: 'The Corries' } },
  { id: 133, lat: 53.4808,  lng: -2.2426,   country: 'UK',               city: 'Manchester',         song: { title: 'Love Will Tear Us Apart',        artist: 'Joy Division' } },
  { id: 134, lat: 51.2093,  lng: 3.2247,    country: 'Belgium',          city: 'Bruges',             song: { title: 'Plaisir d\'Amour',               artist: 'Nana Mouskouri' } },
  { id: 135, lat: 51.9225,  lng: 4.4792,    country: 'Netherlands',      city: 'Rotterdam',          song: { title: 'Rotterdam',                      artist: 'The Beautiful South' } },
  { id: 136, lat: 50.0647,  lng: 19.9450,   country: 'Poland',           city: 'Kraków',             song: { title: 'Hej Sokoly',                     artist: 'Traditional Polish' } },
  { id: 137, lat: 59.4370,  lng: 24.7536,   country: 'Estonia',          city: 'Tallinn',            song: { title: 'Koit',                           artist: 'Tanel Padar' } },
  { id: 138, lat: 56.9460,  lng: 24.1059,   country: 'Latvia',           city: 'Riga',               song: { title: 'Riga dimd',                      artist: 'Traditional Latvian' } },
  { id: 139, lat: 54.6872,  lng: 25.2797,   country: 'Lithuania',        city: 'Vilnius',            song: { title: 'Ant Kalno',                      artist: 'Traditional Lithuanian' } },
  { id: 140, lat: 48.1486,  lng: 17.1077,   country: 'Slovakia',         city: 'Bratislava',         song: { title: 'Cervena Ruza',                   artist: 'Traditional Slovak' } },
  { id: 141, lat: 44.4268,  lng: 26.1025,   country: 'Romania',          city: 'Bucharest',          song: { title: 'Dragostea Din Tei',              artist: 'O-Zone' } },
  { id: 142, lat: 50.4501,  lng: 30.5234,   country: 'Ukraine',          city: 'Kyiv',               song: { title: '1944',                           artist: 'Jamala' } },
  { id: 143, lat: 43.8519,  lng: 18.3866,   country: 'Bosnia',           city: 'Sarajevo',           song: { title: 'Vjencanica',                     artist: 'Dino Merlin' } },
  { id: 144, lat: 41.3275,  lng: 19.8187,   country: 'Albania',          city: 'Tirana',             song: { title: 'Magjistarja',                    artist: 'Bleona Qereti' } },
  { id: 145, lat: 35.8989,  lng: 14.5146,   country: 'Malta',            city: 'Valletta',           song: { title: 'Mad About You',                  artist: 'Ira Losco' } },
  { id: 146, lat: 35.1856,  lng: 33.3823,   country: 'Cyprus',           city: 'Nicosia',            song: { title: 'Fuego',                          artist: 'Eleni Foureira' } },
  { id: 147, lat: 40.6401,  lng: 22.9444,   country: 'Greece',           city: 'Thessaloniki',       song: { title: 'Misirlou',                       artist: 'Mikis Theodorakis' } },
  { id: 148, lat: 41.9981,  lng: 21.4254,   country: 'North Macedonia',  city: 'Skopje',             song: { title: 'Kalimankou Denkou',              artist: 'Elena Karagiozova' } },
  { id: 149, lat: 47.0105,  lng: 28.8638,   country: 'Moldova',          city: 'Chisinau',           song: { title: 'Run Away',                       artist: 'Sunstroke Project' } },
  { id: 150, lat: 49.6117,  lng: 6.1319,    country: 'Luxembourg',       city: 'Luxembourg City',    song: { title: 'Apres toi',                      artist: 'Vicky Leandros' } },
  // Africa (additional)
  { id: 151, lat: 9.0250,   lng: 38.7469,   country: 'Ethiopia',         city: 'Addis Ababa',        song: { title: 'Tizita',                         artist: 'Mulatu Astatke' } },
  { id: 152, lat: -6.7924,  lng: 39.2083,   country: 'Tanzania',         city: 'Dar es Salaam',      song: { title: 'Malaika',                        artist: 'Fadhili William' } },
  { id: 153, lat: 0.3476,   lng: 32.5825,   country: 'Uganda',           city: 'Kampala',            song: { title: 'Sitya Loss',                     artist: 'Eddy Kenzo' } },
  { id: 154, lat: 33.5731,  lng: -7.5898,   country: 'Morocco',          city: 'Casablanca',         song: { title: 'As Time Goes By',                artist: 'Dooley Wilson' } },
  { id: 155, lat: 36.8065,  lng: 10.1815,   country: 'Tunisia',          city: 'Tunis',              song: { title: 'El Bnat Mel Ghorba',             artist: 'Saber Rebai' } },
  { id: 156, lat: 31.2001,  lng: 29.9187,   country: 'Egypt',            city: 'Alexandria',         song: { title: 'Ya Mustapha',                    artist: 'Bob Azzam' } },
  { id: 157, lat: -1.9441,  lng: 30.0619,   country: 'Rwanda',           city: 'Kigali',             song: { title: 'Akaburimbo',                     artist: 'Bruce Melodie' } },
  { id: 158, lat: 9.0579,   lng: 7.4951,    country: 'Nigeria',          city: 'Abuja',              song: { title: 'African Queen',                  artist: '2Face Idibia' } },
  { id: 159, lat: -25.9692, lng: 32.5732,   country: 'Mozambique',       city: 'Maputo',             song: { title: 'Mozambique',                     artist: 'Bob Dylan' } },
  { id: 160, lat: -15.4167, lng: 28.2833,   country: 'Zambia',           city: 'Lusaka',             song: { title: 'Tiyende Pamodzi',                artist: 'Traditional Zambian' } },
  { id: 161, lat: -17.8292, lng: 31.0522,   country: 'Zimbabwe',         city: 'Harare',             song: { title: 'Murimi Ndiani',                  artist: 'Thomas Mapfumo' } },
  { id: 162, lat: -8.8383,  lng: 13.2344,   country: 'Angola',           city: 'Luanda',             song: { title: 'Quem Me Dera',                   artist: 'Paulo Flores' } },
  // Asia (additional)
  { id: 163, lat: 24.8607,  lng: 67.0011,   country: 'Pakistan',         city: 'Karachi',            song: { title: 'Ko Ko Korina',                   artist: 'Vital Signs' } },
  { id: 164, lat: 31.5497,  lng: 74.3436,   country: 'Pakistan',         city: 'Lahore',             song: { title: 'Dil Dil Pakistan',               artist: 'Vital Signs' } },
  { id: 165, lat: 27.7172,  lng: 85.3240,   country: 'Nepal',            city: 'Kathmandu',          song: { title: 'Resham Firiri',                  artist: 'Traditional Nepali' } },
  { id: 166, lat: 16.8661,  lng: 96.1951,   country: 'Myanmar',          city: 'Yangon',             song: { title: 'Ma Ba Thu Kyaw',                 artist: 'Sai Htee Saing' } },
  { id: 167, lat: 11.5564,  lng: 104.9282,  country: 'Cambodia',         city: 'Phnom Penh',         song: { title: 'Champa Battambang',              artist: 'Sinn Sisamouth' } },
  { id: 168, lat: 47.8864,  lng: 106.9057,  country: 'Mongolia',         city: 'Ulaanbaatar',        song: { title: 'Urtiin Duu',                     artist: 'Norovbanzad' } },
  { id: 169, lat: 41.6938,  lng: 44.8015,   country: 'Georgia',          city: 'Tbilisi',            song: { title: 'Mravalzhamier',                  artist: 'Traditional Georgian' } },
  { id: 170, lat: 40.1872,  lng: 44.5152,   country: 'Armenia',          city: 'Yerevan',            song: { title: 'Sari Siroun Yar',                artist: 'Komitas' } },
  { id: 171, lat: 40.4093,  lng: 49.8671,   country: 'Azerbaijan',       city: 'Baku',               song: { title: 'Ceyran',                         artist: 'Rashid Behbudov' } },
  { id: 172, lat: 33.8938,  lng: 35.5018,   country: 'Lebanon',          city: 'Beirut',             song: { title: 'Nassam Alayna Al Hawa',          artist: 'Fairouz' } },
  { id: 173, lat: 31.9539,  lng: 35.9106,   country: 'Jordan',           city: 'Amman',              song: { title: 'Ya Msafer Wahdak',               artist: 'Abdel Halim Hafez' } },
  { id: 174, lat: 35.6892,  lng: 51.3890,   country: 'Iran',             city: 'Tehran',             song: { title: 'Joodayee',                       artist: 'Dariush' } },
  { id: 175, lat: 25.0330,  lng: 121.5654,  country: 'Taiwan',           city: 'Taipei',             song: { title: 'The Moon Represents My Heart',   artist: 'Teresa Teng' } },
  { id: 176, lat: 23.5880,  lng: 58.3829,   country: 'Oman',             city: 'Muscat',             song: { title: 'Habibi Dah',                     artist: 'Haifa Wehbe' } },
  { id: 177, lat: 25.2854,  lng: 51.5310,   country: 'Qatar',            city: 'Doha',               song: { title: 'Tala al Badr Alayna',            artist: 'Traditional Islamic' } },
  { id: 178, lat: 29.3759,  lng: 47.9774,   country: 'Kuwait',           city: 'Kuwait City',        song: { title: 'Ana Bahebak',                    artist: 'Nawal Al Kuwaitia' } },
  { id: 179, lat: 37.9601,  lng: 58.3261,   country: 'Turkmenistan',     city: 'Ashgabat',           song: { title: 'Layli Layli',                    artist: 'Traditional Turkmen' } },
  { id: 180, lat: 42.8746,  lng: 74.5698,   country: 'Kyrgyzstan',       city: 'Bishkek',            song: { title: 'Kara Jorgo',                     artist: 'Traditional Kyrgyz' } },
  { id: 181, lat: 38.5598,  lng: 68.7870,   country: 'Tajikistan',       city: 'Dushanbe',           song: { title: 'Ey Vatan',                       artist: 'Daleri Navruz' } },
  { id: 182, lat: 34.5289,  lng: 69.1723,   country: 'Afghanistan',      city: 'Kabul',              song: { title: 'Ahmad Shah Baba',                artist: 'Traditional Afghan' } },
  { id: 183, lat: 18.7883,  lng: 98.9853,   country: 'Thailand',         city: 'Chiang Mai',         song: { title: 'Sabai Sabai',                    artist: 'Carabao' } },
  { id: 184, lat: 22.5429,  lng: 114.0596,  country: 'China',            city: 'Shenzhen',           song: { title: 'Xiao Ping Guo',                  artist: 'Chopstick Brothers' } },
  // Oceania (additional)
  { id: 185, lat: -34.9285, lng: 138.6007,  country: 'Australia',        city: 'Adelaide',           song: { title: 'Eagle Rock',                     artist: 'Daddy Cool' } },
  { id: 186, lat: -28.0167, lng: 153.4000,  country: 'Australia',        city: 'Gold Coast',         song: { title: 'Boys Light Up',                  artist: 'Australian Crawl' } },
  { id: 187, lat: -43.5321, lng: 172.6362,  country: 'New Zealand',      city: 'Christchurch',       song: { title: 'Better Be Home Soon',            artist: 'Crowded House' } },
  { id: 188, lat: -18.1416, lng: 178.4419,  country: 'Fiji',             city: 'Suva',               song: { title: 'Isa Lei',                        artist: 'Traditional Fijian' } },
  { id: 189, lat: -9.4438,  lng: 147.1803,  country: 'Papua New Guinea', city: 'Port Moresby',       song: { title: 'Sing Sing',                      artist: 'Traditional Melanesian' } },
  { id: 190, lat: 21.3069,  lng: -157.8583, country: 'USA',              city: 'Honolulu',           song: { title: 'Somewhere Over the Rainbow',     artist: 'Israel Kamakawiwoole' } },
  // Central America & Caribbean (additional)
  { id: 191, lat: 17.9970,  lng: -76.7936,  country: 'Jamaica',          city: 'Kingston',           song: { title: 'No Woman No Cry',                artist: 'Bob Marley' } },
  { id: 192, lat: 18.5944,  lng: -72.3074,  country: 'Haiti',            city: 'Port-au-Prince',     song: { title: 'Konpa',                          artist: 'Nemours Jean-Baptiste' } },
  { id: 193, lat: 14.1054,  lng: -87.2169,  country: 'Honduras',         city: 'Tegucigalpa',        song: { title: 'Sopa de Caracol',                artist: 'Banda Blanca' } },
  { id: 194, lat: 14.6349,  lng: -90.5069,  country: 'Guatemala',        city: 'Guatemala City',     song: { title: 'Luna de Xelaju',                 artist: 'Marimba Chapinlandia' } },
  { id: 195, lat: 12.1360,  lng: -86.2771,  country: 'Nicaragua',        city: 'Managua',            song: { title: 'Nicaragua Mia',                  artist: 'Carlos Mejia Godoy' } },
  { id: 196, lat: 13.6929,  lng: -89.2182,  country: 'El Salvador',      city: 'San Salvador',       song: { title: 'El Carbonero',                   artist: 'Los Hermanos Flores' } },
  // Remote & Unique (additional)
  { id: 197, lat: 43.2965,  lng: 5.3698,    country: 'France',           city: 'Marseille',          song: { title: 'La Marseillaise',                artist: 'Claude Joseph Rouget de Lisle' } },
  { id: 198, lat: 46.9480,  lng: 7.4474,    country: 'Switzerland',      city: 'Bern',               song: { title: 'Egoist',                         artist: 'DJ Bobo' } },
  { id: 199, lat: 69.6492,  lng: 18.9553,   country: 'Norway',           city: 'Tromsø',             song: { title: 'Runaway',                        artist: 'Aurora' } },
  { id: 200, lat: 38.1157,  lng: 13.3615,   country: 'Italy',            city: 'Palermo',            song: { title: 'Bella Ciao',                     artist: 'Traditional Italian' } },
];
